package application.domain.valueObjects;

public enum OperationType {

    SELLER_REGISTERED,
    WAREHOUSE_REGISTERED,
    PRODUCT_PUBLISHED,
    INVENTORY_ADJUSTED,
    ORDER_CREATED,
    PAYMENT_CONFIRMED,
    ORDER_DISPATCHED,
    ORDER_DELIVERED,
    SHIPMENT_PREPARED,
    SHIPMENT_DISPATCHED,
    SHIPMENT_DELIVERED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    REFUND_PROCESSED,
    REFUND_REJECTED,
    INVOICE_ISSUED

}
